import assert from 'node:assert/strict';
import { EventEmitter } from 'node:events';
import { AvatarSessionError, parseAvatarWorkerStatus, avatarWorkerError, waitForAvatarWorker } from '../src/lib/avatarStatus.ts';

const ready = JSON.stringify({ voice: { version: 1, state: 'ready' } });
const failure = JSON.stringify({ voice: { version: 1, state: 'error', code: 'provider_credits' } });
class Room extends EventEmitter { metadata = ''; }
assert.equal(parseAvatarWorkerStatus('malformed'), null);
assert.equal(parseAvatarWorkerStatus('{"voice":null}'), null);
assert.equal(parseAvatarWorkerStatus('{"voice":{"version":2,"state":"ready"}}'), null);
assert.equal(parseAvatarWorkerStatus(failure).code, 'provider_credits');
assert.ok(!avatarWorkerError(parseAvatarWorkerStatus(failure)).message.includes('credits'));
const room = new Room();
room.metadata = failure;
await assert.rejects(waitForAvatarWorker(room, new AbortController().signal), error => error instanceof AvatarSessionError && error.message.includes('tidak tersedia'));
assert.equal(room.listenerCount('roomMetadataChanged'), 0);
room.metadata = ready;
await waitForAvatarWorker(room, new AbortController().signal);
assert.equal(room.listenerCount('roomMetadataChanged'), 0);
room.metadata = '';
const pending = waitForAvatarWorker(room, new AbortController().signal);
room.emit('roomMetadataChanged', 'invalid');
room.emit('roomMetadataChanged', failure);
await assert.rejects(pending, AvatarSessionError);
assert.equal(room.listenerCount('roomMetadataChanged'), 0);
const success = waitForAvatarWorker(room, new AbortController().signal);
room.emit('roomMetadataChanged', ready);
await success;
assert.equal(room.listenerCount('roomMetadataChanged'), 0);
const controller = new AbortController();
const aborted = waitForAvatarWorker(room, controller.signal);
controller.abort();
await assert.rejects(aborted, error => error.name === 'AbortError');
assert.equal(room.listenerCount('roomMetadataChanged'), 0);
await assert.rejects(waitForAvatarWorker(room, new AbortController().signal, 1), error => error instanceof AvatarSessionError && error.message.includes('terlalu lama'));
assert.equal(room.listenerCount('roomMetadataChanged'), 0);
console.log('PASS: failure before join, failure after join, readiness, invalid metadata, timeout, cancellation and listener cleanup.');
